name: Build Dumper

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем исходники
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Компилируем через NDK
        run: |
          cd AndUEDumper
          $ANDROID_NDK_LATEST_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk

      - name: Загружаем готовый результат
        uses: actions/upload-artifact@v4
        with:
          name: Dumper-Compiled
          path: AndUEDumper/libs/
